function converterMaiusculas(array){
  for (let i = 0;i<array.length;i++){
    array[i] = array[i].toUpperCase();
  }
  console.table(array);
}

function pasajeDeElementos(array1, array2){
  array.push(array2.pop(). toUpperCase())
}


function converterMaiusculas(array){
  let arrRetorno =[]
    for(let i=0;i<array.length;i++){
      arrayRetorno =[i] = array [i] +"a";
    }
  return arrRetorno;
}

function pasajeDeElementos(array1, array2){
  array1.push(array2.pop(). toUpperCase())
  array1.push(array2.pop(). toUpperCase())
  array1.push(array2.pop(). toUpperCase())
  array1.push(array2.pop(). toUpperCase())
  array1.push(array2.pop(). toUpperCase())
}
function passarElementosDeUmArrayParaOutro (array1,array2){
  let arr1Upper = converterMaiusculas(array);
  for (let i=0; i<array2.lenght;i++){
    arrUpper.push(array2[i].toUpperCase())
  }
  return arr1Upeer;
}
let arrUpper = passarElementosDeUmArrayParaOutro (filmes,filmes2);
console.table (arrUpper.sort());
function passarElementosDeUmArrayParaOutro(filmes,filmes2);
/*3*/
const

function compararCalificaciones(asia,europa){
  let comparacionesAsiaEuropa =[]
  comparacionesAsiaEuropa[0]= asia[0]= europa[0]
  comparacionesAsiaEuropa[1]= asia[1]= europa[1]
  comparacionesAsiaEuropa[2]= asia[2]= europa[2]
  comparacionesAsiaEuropa[3]= asia[3]= europa[3]
}
console.table (arrUpper.sort());